use fastembed::{EmbeddingModel, InitOptions, TextEmbedding};
use ort::execution_providers::coreml::CoreMLComputeUnits;
use ort::execution_providers::CoreMLExecutionProvider;

fn main() -> anyhow::Result<()> {
    // 1. Create a list of providers using the documented API.
    let providers = vec![
        // CoreMLExecutionProvider::default()
        //     // Provide a boolean argument to enable subgraphs
        //     .with_subgraphs(true)
        //     // .with_ane_only()
        //     // .with_compute_units(CoreMLComputeUnits::CPUAndNeuralEngine)
        //     // .with_compute_units(CoreMLComputeUnits::CPUAndGPU)
        //     .with_compute_units(CoreMLComputeUnits::CPUOnly)
        //     .build(),
        // // The CPU provider is used automatically as a fallback
    ];

    // 2. Create InitOptions and pass the configured providers.
    let init_options =
        InitOptions::new(EmbeddingModel::BGELargeENV15).with_execution_providers(providers);

    // 3. Initialize the model.
    let mut model = TextEmbedding::try_new(init_options)?;

    println!("Model initialized successfully with CoreML provider!");

    // Expanded list of documents for batch processing
    let documents = vec![
        "This is a test document running on Apple Silicon.",
        "The quick brown fox jumps over the lazy dog.",
        "FastEmbed is a high-performance library for text embeddings.",
        "Rust is a systems programming language focused on safety and performance.",
        "The Apple Neural Engine accelerates machine learning tasks.",
        "What is the capital of Nicaragua?",
        "The sun rises in the east and sets in the west.",
        "Large language models are trained on vast amounts of text data.",
        "Natural language processing is a subfield of artificial intelligence.",
        "The Pacific Ocean is the largest and deepest of the world's five oceans.",
        "A recipe for chocolate chip cookies usually includes flour, sugar, butter, and eggs.",
        "Quantum computing leverages principles of quantum mechanics.",
        "The speed of light in a vacuum is approximately 299,792 kilometers per second.",
        "Machine learning models can be used for classification, regression, and clustering.",
        "The human brain contains about 86 billion neurons.",
        "Paris is the capital city of France.",
        "To be or not to be, that is the question.",
        "All that glitters is not gold.",
        "The early bird catches the worm.",
        "Where there is a will, there is a way.",
        "A journey of a thousand miles begins with a single step.",
        "Honesty is the best policy.",
        "Laughter is the best medicine.",
        "The cat sat on the mat.",
        "Exploring the capabilities of modern hardware.",
        "Batch processing is more efficient than single-item processing.",
        "Vector embeddings represent text in a high-dimensional space.",
        "Cosine similarity is a measure of similarity between two non-zero vectors.",
        "This library leverages ONNX Runtime for inference.",
        "CoreML is Apple's framework for on-device machine learning.",
        "Artificial intelligence is transforming many industries.",
        "Hello, world! This is a classic programming phrase.",
        "Let's add a few more sentences to reach our goal.",
        "This sentence is just here to add more data to the batch.",
        "Another string for the vector.",
        "The model will process all of these documents at once.",
        "How well does this model handle different languages?",
        "¿Se puede procesar texto en español?",
        "Ceci est une phrase en français.",
        "Dies ist ein Satz auf Deutsch.",
        "The model should be robust to various inputs.",
        "Testing the limits of batch size.",
        "Finalizing the list of documents.",
        "The mission of the Apollo 11 was to land humans on the Moon.",
        "Water is composed of hydrogen and oxygen atoms.",
        "The Internet is a global network of interconnected computers.",
        "What is the meaning of life?",
        "Another document to increase the batch size.",
        "Final sentence for this large batch.",
        "We have now surpassed fifty documents.",
        "This ensures a thorough test of the batching functionality.",
        "This is a test document running on Apple Silicon.",
        "The quick brown fox jumps over the lazy dog.",
        "FastEmbed is a high-performance library for text embeddings.",
        "Rust is a systems programming language focused on safety and performance.",
        "The Apple Neural Engine accelerates machine learning tasks.",
        "What is the capital of Nicaragua?",
        "The sun rises in the east and sets in the west.",
        "Large language models are trained on vast amounts of text data.",
        "Natural language processing is a subfield of artificial intelligence.",
        "The Pacific Ocean is the largest and deepest of the world's five oceans.",
        "A recipe for chocolate chip cookies usually includes flour, sugar, butter, and eggs.",
        "Quantum computing leverages principles of quantum mechanics.",
        "The speed of light in a vacuum is approximately 299,792 kilometers per second.",
        "Machine learning models can be used for classification, regression, and clustering.",
        "The human brain contains about 86 billion neurons.",
        "Paris is the capital city of France.",
        "To be or not to be, that is the question.",
        "All that glitters is not gold.",
        "The early bird catches the worm.",
        "Where there is a will, there is a way.",
        "A journey of a thousand miles begins with a single step.",
        "Honesty is the best policy.",
        "Laughter is the best medicine.",
        "The cat sat on the mat.",
        "Exploring the capabilities of modern hardware.",
        "Batch processing is more efficient than single-item processing.",
        "Vector embeddings represent text in a high-dimensional space.",
        "Cosine similarity is a measure of similarity between two non-zero vectors.",
        "This library leverages ONNX Runtime for inference.",
        "CoreML is Apple's framework for on-device machine learning.",
        "Artificial intelligence is transforming many industries.",
        "Hello, world! This is a classic programming phrase.",
        "Let's add a few more sentences to reach our goal.",
        "This sentence is just here to add more data to the batch.",
        "Another string for the vector.",
        "The model will process all of these documents at once.",
        "How well does this model handle different languages?",
        "¿Se puede procesar texto en español?",
        "Ceci est une phrase en français.",
        "Dies ist ein Satz auf Deutsch.",
        "The model should be robust to various inputs.",
        "Testing the limits of batch size.",
        "Finalizing the list of documents.",
        "The mission of the Apollo 11 was to land humans on the Moon.",
        "Water is composed of hydrogen and oxygen atoms.",
        "The Internet is a global network of interconnected computers.",
        "What is the meaning of life?",
        "Another document to increase the batch size.",
        "Final sentence for this large batch.",
        "We have now surpassed fifty documents.",
        "This ensures a thorough test of the batching functionality.",
        "This is a test document running on Apple Silicon.",
        "The quick brown fox jumps over the lazy dog.",
        "FastEmbed is a high-performance library for text embeddings.",
        "Rust is a systems programming language focused on safety and performance.",
        "The Apple Neural Engine accelerates machine learning tasks.",
        "What is the capital of Nicaragua?",
        "The sun rises in the east and sets in the west.",
        "Large language models are trained on vast amounts of text data.",
        "Natural language processing is a subfield of artificial intelligence.",
        "The Pacific Ocean is the largest and deepest of the world's five oceans.",
        "A recipe for chocolate chip cookies usually includes flour, sugar, butter, and eggs.",
        "Quantum computing leverages principles of quantum mechanics.",
        "The speed of light in a vacuum is approximately 299,792 kilometers per second.",
        "Machine learning models can be used for classification, regression, and clustering.",
        "The human brain contains about 86 billion neurons.",
        "Paris is the capital city of France.",
        "To be or not to be, that is the question.",
        "All that glitters is not gold.",
        "The early bird catches the worm.",
        "Where there is a will, there is a way.",
        "A journey of a thousand miles begins with a single step.",
        "Honesty is the best policy.",
        "Laughter is the best medicine.",
        "The cat sat on the mat.",
        "Exploring the capabilities of modern hardware.",
        "Batch processing is more efficient than single-item processing.",
        "Vector embeddings represent text in a high-dimensional space.",
        "Cosine similarity is a measure of similarity between two non-zero vectors.",
        "This library leverages ONNX Runtime for inference.",
        "CoreML is Apple's framework for on-device machine learning.",
        "Artificial intelligence is transforming many industries.",
        "Hello, world! This is a classic programming phrase.",
        "Let's add a few more sentences to reach our goal.",
        "This sentence is just here to add more data to the batch.",
        "Another string for the vector.",
        "The model will process all of these documents at once.",
        "How well does this model handle different languages?",
        "¿Se puede procesar texto en español?",
        "Ceci est une phrase en français.",
        "Dies ist ein Satz auf Deutsch.",
        "The model should be robust to various inputs.",
        "Testing the limits of batch size.",
        "Finalizing the list of documents.",
        "The mission of the Apollo 11 was to land humans on the Moon.",
        "Water is composed of hydrogen and oxygen atoms.",
        "The Internet is a global network of interconnected computers.",
        "What is the meaning of life?",
        "Another document to increase the batch size.",
        "Final sentence for this large batch.",
        "We have now surpassed fifty documents.",
        "This ensures a thorough test of the batching functionality.",
        "This is a test document running on Apple Silicon.",
        "The quick brown fox jumps over the lazy dog.",
        "FastEmbed is a high-performance library for text embeddings.",
        "Rust is a systems programming language focused on safety and performance.",
        "The Apple Neural Engine accelerates machine learning tasks.",
        "What is the capital of Nicaragua?",
        "The sun rises in the east and sets in the west.",
        "Large language models are trained on vast amounts of text data.",
        "Natural language processing is a subfield of artificial intelligence.",
        "The Pacific Ocean is the largest and deepest of the world's five oceans.",
        "A recipe for chocolate chip cookies usually includes flour, sugar, butter, and eggs.",
        "Quantum computing leverages principles of quantum mechanics.",
        "The speed of light in a vacuum is approximately 299,792 kilometers per second.",
        "Machine learning models can be used for classification, regression, and clustering.",
        "The human brain contains about 86 billion neurons.",
        "Paris is the capital city of France.",
        "To be or not to be, that is the question.",
        "All that glitters is not gold.",
        "The early bird catches the worm.",
        "Where there is a will, there is a way.",
        "A journey of a thousand miles begins with a single step.",
        "Honesty is the best policy.",
        "Laughter is the best medicine.",
        "The cat sat on the mat.",
        "Exploring the capabilities of modern hardware.",
        "Batch processing is more efficient than single-item processing.",
        "Vector embeddings represent text in a high-dimensional space.",
        "Cosine similarity is a measure of similarity between two non-zero vectors.",
        "This library leverages ONNX Runtime for inference.",
        "CoreML is Apple's framework for on-device machine learning.",
        "Artificial intelligence is transforming many industries.",
        "Hello, world! This is a classic programming phrase.",
        "Let's add a few more sentences to reach our goal.",
        "This sentence is just here to add more data to the batch.",
        "Another string for the vector.",
        "The model will process all of these documents at once.",
        "How well does this model handle different languages?",
        "¿Se puede procesar texto en español?",
        "Ceci est une phrase en français.",
        "Dies ist ein Satz auf Deutsch.",
        "The model should be robust to various inputs.",
        "Testing the limits of batch size.",
        "Finalizing the list of documents.",
        "The mission of the Apollo 11 was to land humans on the Moon.",
        "Water is composed of hydrogen and oxygen atoms.",
        "The Internet is a global network of interconnected computers.",
        "What is the meaning of life?",
        "Another document to increase the batch size.",
        "Final sentence for this large batch.",
        "We have now surpassed fifty documents.",
        "This ensures a thorough test of the batching functionality.",
        "This is a test document running on Apple Silicon.",
        "The quick brown fox jumps over the lazy dog.",
        "FastEmbed is a high-performance library for text embeddings.",
        "Rust is a systems programming language focused on safety and performance.",
        "The Apple Neural Engine accelerates machine learning tasks.",
        "What is the capital of Nicaragua?",
        "The sun rises in the east and sets in the west.",
        "Large language models are trained on vast amounts of text data.",
        "Natural language processing is a subfield of artificial intelligence.",
        "The Pacific Ocean is the largest and deepest of the world's five oceans.",
        "A recipe for chocolate chip cookies usually includes flour, sugar, butter, and eggs.",
        "Quantum computing leverages principles of quantum mechanics.",
        "The speed of light in a vacuum is approximately 299,792 kilometers per second.",
        "Machine learning models can be used for classification, regression, and clustering.",
        "The human brain contains about 86 billion neurons.",
        "Paris is the capital city of France.",
        "To be or not to be, that is the question.",
        "All that glitters is not gold.",
        "The early bird catches the worm.",
        "Where there is a will, there is a way.",
        "A journey of a thousand miles begins with a single step.",
        "Honesty is the best policy.",
        "Laughter is the best medicine.",
        "The cat sat on the mat.",
        "Exploring the capabilities of modern hardware.",
        "Batch processing is more efficient than single-item processing.",
        "Vector embeddings represent text in a high-dimensional space.",
        "Cosine similarity is a measure of similarity between two non-zero vectors.",
        "This library leverages ONNX Runtime for inference.",
        "CoreML is Apple's framework for on-device machine learning.",
        "Artificial intelligence is transforming many industries.",
        "Hello, world! This is a classic programming phrase.",
        "Let's add a few more sentences to reach our goal.",
        "This sentence is just here to add more data to the batch.",
        "Another string for the vector.",
        "The model will process all of these documents at once.",
        "How well does this model handle different languages?",
        "¿Se puede procesar texto en español?",
        "Ceci est une phrase en français.",
        "Dies ist ein Satz auf Deutsch.",
        "The model should be robust to various inputs.",
        "Testing the limits of batch size.",
        "Finalizing the list of documents.",
        "The mission of the Apollo 11 was to land humans on the Moon.",
        "Water is composed of hydrogen and oxygen atoms.",
        "The Internet is a global network of interconnected computers.",
        "What is the meaning of life?",
        "Another document to increase the batch size.",
        "Final sentence for this large batch.",
        "We have now surpassed fifty documents.",
        "This ensures a thorough test of the batching functionality.",
    ];

    println!("Processing a batch of {} documents...", documents.len());
    let embeddings = model.embed(documents, Some(32))?;

    println!(
        "Successfully generated {} embeddings using the Neural Engine.",
        embeddings.len()
    );
    // Optionally, print the dimension of the first embedding to verify
    if let Some(first_embedding) = embeddings.first() {
        println!("Embedding vector dimension: {}", first_embedding.len());
    }

    Ok(())
}
